# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33d01cb559b361daffa3285ce22310d8c9a6115cec5a23a438aaff43e3d16e62148fed04a1c86ee6e618c6139a8b1293866ab638282af67447199a7d33b84100

test:
  secret_key_base: e3ec62b3b8d9a24ff45d59acfc2f2345e3e9bd323da17844d2753fc990950964ed61b9666cdb56bfdb7f093944e3eabf08e1d44d2d43b74e87d8faa52d4ba388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
